### PR TITLE
Changes to upgrade to Microsoft.Logging.Extensions v7

### PR DESCRIPTION
**Pull request by dantdj**
Upgrading to allow use with Microsoft.Logging.Extensions v7.

Removing references to the older .NET Core versions as well, as they've fallen out of support and seemingly aren't supported by v7 of the logging library.

I've done my best to clear up any older references - please let me know what else might need doing, or if I've been too eager in cleaning some parts up!

### CODE REVIEW

**Comment by dantdj** [comment]
@kparkinson-ld - I see you're marked as a contributor on this repo now - would you be able to review this, or know who might be able to on the LD side?

**Comment by dantdj** [comment]
I see @launchdarkly/team-sdk is in the codeowners file but that doesn't seem to be something I can tag

**Comment by kparkinson-ld** [comment]
> I see @launchdarkly/team-sdk is in the codeowners file but that doesn't seem to be something I can tag

It may be that you don't have permission to see our teams. I will tag them for you and make a note to look into this.

**Comment by dantdj** [comment]
Thanks @kparkinson-ld, really appreciate it!

**Comment by kinyoklion** [comment]
Hey @dantdj,

Sorry this PR flew under the radar. It has been superseded by another PR and I am resolving some things with the release process and CI.

**Comment by kinyoklion** [comment]
Hey @dantdj,

Again, thank you for your contribution. This has now been released with version 3.1. 

I am closing this PR, but let me know if everything works for you.

Thank you,
Ryan

**Comment by dantdj** [comment]
Hey @kinyoklion - no worries, thanks for picking the update up!

**Pull request closed without merging**
